<?php
function form_riverdelta_menu() {
  $items = array();
  $items['form_riverdelta'] = array(
    'title' => 'Required Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_riverdelta_custom'),
    'access callback' => TRUE,
    'description' => 'Required field tutorial',
    'file' => 'form_riverdelta_custom.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_help().
 */
function form_riverdelta_help($path, $arg) {
  switch ($path) {
    case 'form_riverdelta':
      // TODO: Update the URL.
      $help = t('');
      break;
  }
  if (!empty($help)) {
    return '<p>' . $help . '</p>';
  }
}


